"""increase size of concept_cd from 50 to 100

Revision ID: 8fa311650544
Revises: b7a3e293c207
Create Date: 2017-11-21 11:50:52.859952

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa311650544'
down_revision = 'b7a3e293c207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concept_dimension', 'concept_cd',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('encounter_mapping', 'encounter_num',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('encounter_num_seq'::regclass)"))
    op.alter_column('observation_fact', 'concept_cd',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100))
    op.alter_column('patient_mapping', 'patient_num',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('patient_num_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_mapping', 'patient_num',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('patient_num_seq'::regclass)"))
    op.alter_column('observation_fact', 'concept_cd',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50))
    op.alter_column('encounter_mapping', 'encounter_num',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('encounter_num_seq'::regclass)"))
    op.alter_column('concept_dimension', 'concept_cd',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
