"""add patient_age column to visit_dimension

Revision ID: d75dce0b483a
Revises: 7404cf411ca9
Create Date: 2017-03-08 15:25:21.745400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75dce0b483a'
down_revision = '7404cf411ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_dimension', sa.Column('patient_age', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_dimension', 'patient_age')
    # ### end Alembic commands ###
