"""explicit NOT NULL constraint on sequences

Revision ID: ee9874f3a8f0
Revises: 8fa311650544
Create Date: 2017-11-28 10:30:16.930391

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9874f3a8f0'
down_revision = '8fa311650544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encounter_mapping', 'encounter_num',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('encounter_num_seq'::regclass)"))
    op.alter_column('patient_mapping', 'patient_num',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('patient_num_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_mapping', 'patient_num',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('patient_num_seq'::regclass)"))
    op.alter_column('encounter_mapping', 'encounter_num',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('encounter_num_seq'::regclass)"))
    # ### end Alembic commands ###
