"""init

Revision ID: f50b303505b6
Revises: 
Create Date: 2017-02-01 18:50:34.943586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50b303505b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_lookup',
    sa.Column('table_cd', sa.VARCHAR(length=100), nullable=False),
    sa.Column('column_cd', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code_cd', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name_char', sa.VARCHAR(length=650), nullable=True),
    sa.Column('lookup_blob', sa.TEXT(), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('table_cd', 'column_cd', 'code_cd')
    )
    op.create_table('concept_dimension',
    sa.Column('concept_path', sa.VARCHAR(length=700), nullable=False),
    sa.Column('concept_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name_char', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('concept_blob', sa.TEXT(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('concept_path')
    )
    op.create_table('encounter_mapping',
    sa.Column('encounter_ide', sa.VARCHAR(length=200), nullable=False),
    sa.Column('encounter_ide_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('encounter_num', sa.INTEGER(), nullable=False),
    sa.Column('patient_ide', sa.VARCHAR(length=200), nullable=False),
    sa.Column('patient_ide_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('encounter_ide_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('encounter_ide', 'encounter_ide_source', 'project_id', 'patient_ide', 'patient_ide_source')
    )
    op.create_table('modifier_dimension',
    sa.Column('concept_path', sa.VARCHAR(length=700), nullable=False),
    sa.Column('concept_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name_char', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('modifier_blob', sa.TEXT(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('concept_path')
    )
    op.create_table('observation_fact',
    sa.Column('encounter_num', sa.INTEGER(), nullable=False),
    sa.Column('concept_cd', sa.VARCHAR(length=50), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('patient_num', sa.INTEGER(), nullable=False),
    sa.Column('modifier_cd', sa.CHAR(length=50), server_default='@', nullable=False),
    sa.Column('instance_num', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('valtype_cd', sa.CHAR(length=50), nullable=True),
    sa.Column('tval_char', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nval_num', sa.DECIMAL(precision=18, scale=5), nullable=True),
    sa.Column('valueflag_cd', sa.CHAR(length=50), nullable=True),
    sa.Column('quantity_num', sa.DECIMAL(precision=18, scale=5), nullable=True),
    sa.Column('units_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('location_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('observation_blob', sa.TEXT(), nullable=True),
    sa.Column('confidence_num', sa.DECIMAL(precision=18, scale=5), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('encounter_num', 'concept_cd', 'provider_id', 'start_date', 'patient_num', 'modifier_cd', 'instance_num')
    )
    op.create_table('patient_dimension',
    sa.Column('patient_num', sa.INTEGER(), nullable=False),
    sa.Column('vital_status_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('birth_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('death_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sex_cd', sa.CHAR(length=50), nullable=True),
    sa.Column('age_in_years_num', sa.INTEGER(), nullable=True),
    sa.Column('language_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('race_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marital_status_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('religion_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zip_cd', sa.VARCHAR(length=10), nullable=True),
    sa.Column('statecityzip_path', sa.VARCHAR(length=700), nullable=True),
    sa.Column('income_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('patient_blob', sa.TEXT(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('patient_num')
    )
    op.create_table('patient_mapping',
    sa.Column('patient_ide', sa.VARCHAR(length=200), nullable=False),
    sa.Column('patient_ide_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('patient_num', sa.INTEGER(), nullable=True),
    sa.Column('patient_ide_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('patient_ide', 'patient_ide_source', 'project_id'),
    sa.UniqueConstraint('patient_num')
    )
    op.create_table('provider_dimension',
    sa.Column('provider_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('provider_path', sa.VARCHAR(length=700), nullable=False),
    sa.Column('name_char', sa.VARCHAR(length=850), nullable=True),
    sa.Column('provider_blob', sa.TEXT(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('provider_id', 'provider_path')
    )
    op.create_table('visit_dimension',
    sa.Column('encounter_num', sa.INTEGER(), nullable=False),
    sa.Column('patient_num', sa.INTEGER(), nullable=False),
    sa.Column('active_status_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('inout_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location_path', sa.VARCHAR(length=900), nullable=True),
    sa.Column('length_if_stay', sa.INTEGER(), nullable=True),
    sa.Column('visit_blob', sa.TEXT(), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('import_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sourcesystem_cd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upload_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('encounter_num', 'patient_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_dimension')
    op.drop_table('provider_dimension')
    op.drop_table('patient_mapping')
    op.drop_table('patient_dimension')
    op.drop_table('observation_fact')
    op.drop_table('modifier_dimension')
    op.drop_table('encounter_mapping')
    op.drop_table('concept_dimension')
    op.drop_table('code_lookup')
    # ### end Alembic commands ###
